.PHONY: clean All

All:
	@echo "----------Building project:[ apt32f102 - BuildSet ]----------"
	@cd "C:\Users\yupp.APT-HZ\Desktop\APT32F102_Release_V0_50_20190715\Source" && make -f  "apt32f102.mk"
clean:
	@echo "----------Cleaning project:[ apt32f102 - BuildSet ]----------"
	@cd "C:\Users\yupp.APT-HZ\Desktop\APT32F102_Release_V0_50_20190715\Source" && make -f  "apt32f102.mk" clean
