.PHONY: clean All

All:
	@echo "----------Building project:[ apt32f102 - BuildSet ]----------"
	@
	@cd "E:\os\atomthread\ck8xx_atomthreads\atomthreadsCK8xx\Source" && make -f "apt32f102.mk" MakeIntermediateDirs && make -f "apt32f102.mk" -j 2
clean:
	@echo "----------Cleaning project:[ apt32f102 - BuildSet ]----------"
	@cd "E:\os\atomthread\ck8xx_atomthreads\atomthreadsCK8xx\Source" && make -f  "apt32f102.mk" clean
